spring:
  profiles:
    active: pro
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

comment.avatar: /asserts/images/avatar.png

alibaba:
  cloud:
    access-key: xxxxxxxxxxxx
    secret-key: xxxxxxxxxxxxx
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com